tinyMCE.addI18n('en.jwplayer_dlg',{
  'always' : 'Always',
  'autostart' : 'Autostart',
  'behavior' : 'Behavior',
  'bottom' : 'Bottom',
  'control_bar' : 'Control bar',
  'controlbar_position' : 'Control bar position',
  'exact_fit' : 'Exact fit',
  'file' : 'File',
  'fill' : 'Fill',
  'general' : 'General',
  'height' : 'Height',
  'image' : 'Image',
  'layout' : 'Layout',
  'left' : 'Left',
  'list' : 'List',
  'no' : 'No',
  'none' : 'None',
  'over' : 'Over',
  'playlist' : 'Playlist',
  'playlist_file' : 'Playlist file',
  'playlist_position' : 'Playlist position',
  'playlist_size' : 'Playlist size',
  'repeat' : 'Repeat',
  'right' : 'Right',
  'single' : 'Single',
  'shuffle' : 'Shuffle',
  'size' : 'Size',
  'streamer' : 'Streamer',
  'stretching' : 'Stretching',
  'title' : 'Insert/Edit JwPlayer',
  'top' : 'Top',
  'uniform' : 'Uniform',
  'width' : 'Width',
  'yes' : 'Yes'
});
