tinyMCE.addI18n('fr.jwplayer_dlg',{
  'behavior' : 'Comportement',
  'bottom' : 'En bas',
  'control_bar' : 'Barre de contrôles',
  'controlbar_position' : 'Position de la barre de contrôles',
  'exact_fit' : 'Ajustement exact',
  'file' : 'Fichier',
  'fill' : 'Remplir',
  'general' : 'General',
  'height' : 'Hauteur',
  'image' : 'Image',
  'layout' : 'Présentation',
  'left' : 'Gauche',
  'none' : 'Aucun',
  'over' : 'Par dessus',
  'playlist' : 'Liste de lecture',
  'playlist_file' : 'Fichier de liste de lecture',
  'playlist_position' : 'Position de la liste de lecture',
  'playlist_size' : 'Taille de la liste de lecture',
  'right' : 'Droite',
  'size' : 'Taille',
  'streamer' : 'Serveur de stream',
  'stretching' : 'Etirement',
  'title' : 'Inserer/Editer un JwPlayer',
  'top' : 'Haut',
  'uniform' : 'Uniforme',
  'width' : 'Largeur'
});
